GET http://127.0.0.1:8000/users/

###
GET http://127.0.0.1:8000/users/1


###
POST http://127.0.0.1:8000/user/post/
Content-Type: application/json

{
    "name": "vanelle",
}


### 
PATCH http://127.0.0.1:8000/user/post/
Content-Type: application/json

{
    "name": "vanelle",
}

